# Load pre-calculated data generated by S_stercoralis_Data_Analysis/Processing.R
# 
# Import a variance-stabilized DEGList created by voom transformation command.
# Outputs: E = normalized CPMexpression values on the log2 scale
load(file = "./vDEGList")

# Import a tidy dataframe containing an Ensembl Compara protein family set
# Origin: Hunt et al 2016
# Note that this uses specific transcript information, which I throw out. 
# (e.g. SSTP_0001137400.2 is recoded as SSTP_0001137400)
load(file = "./parasiteGeneSets")


# Parse vDEGList into a tibble containing Log2CPM information
Log2CPM<-v.DEGList.filtered.norm$E %>%
    as_tibble(rownames = "geneID")%>%
    setNames(nm = c("geneID", 
                    as.character(v.DEGList.filtered.norm$targets$group))) %>%
    pivot_longer(cols = -geneID,
                 names_to = "life_stage", 
                 values_to = "log2CPM") %>%
    group_by(geneID, life_stage)

diffGenes.df <- v.DEGList.filtered.norm$E %>%
    as_tibble(rownames = "geneID", .name_repair = "unique")

## Fit a linear model to the data ----
fit <- lmFit(v.DEGList.filtered.norm, v.DEGList.filtered.norm$design)


## Set Expression threshold values for plotting and saving DEGs ----
adj.P.thresh <- 0.05
lfc.thresh <- 1