# Load pre-calculated data generated by preprocessing scripts
# 

# Import a tidy dataframe containing an Ensembl Compara protein family set
# Origin: Hunt et al 2016
# Note that this uses specific transcript information, which I throw out. 
# (e.g. SSTP_0001137400.2 is recoded as SSTP_0001137400)
load(file = "./Data/Str_parasiteGeneSets")

# Import a file containing life stage legend terms
lifestage_legend <- suppressMessages(read_tsv("./Data/Life_stage_legend.txt",
                             # col_types = "cc",
         na = c("", "NA", "na")))

## Set Expression threshold values for plotting and saving DEGs ----
adj.P.thresh <- 0.05
lfc.thresh <- 1