# Introduction to Strongyloides stercoralis Tx Import Script ----
# 
# 

# load packages ----
#library(rhdf5) #provides functions for handling hdf5 file formats (kallisto outputs bootstraps in this format)
library(tidyverse) # provides access to Hadley Wickham's collection of R packages for data science, which we will use throughout the course
library(tximport) # package for getting Kallisto results into R
library(ensembldb) # helps deal with ensembl
library(datapasta) # allows user to paste data into R
library(biomaRt) # an alternative for annotation
library(magrittr) # piping
#library(EnsDb.Hsapiens.v86) #replace with your organism-specific database package
#library(beepr) #just for fun


# read in the study design ----
targets <- read_tsv("./Data/PRJEB3116subset.txt")
# you can easily create file paths to the abundance files generated by Kallisto using the 'file.path' function
path <- file.path("./Data",targets$sample, "abundance.tsv") # set file paths to your mapped data
# now check to make sure this path is correct by seeing if the files exist
all(file.exists(path)) 

# get annotations using organism-specific package ----
Tx.Ss <- getBM(attributes=c('wbps_transcript_id',
                            'wbps_gene_id'),
               # grab the ensembl annotations for Wormbase Parasite genes
               mart = useMart(biomart="parasite_mart", 
                              dataset = "wbps_gene", 
                              host="https://parasite.wormbase.org", 
                              port = 443),
               filters = c('species_id_1010'),
               value = list('ststerprjeb528')) %>%
    as_tibble() %>%
    #we need to rename the two columns we just retreived from biomart
    dplyr::rename(target_id = wbps_transcript_id,
                  gene_name = wbps_gene_id) 

# import Kallisto transcript counts into R using Tximport ----
# copy the abundance files to the working directory and rename so that each sample has a unique name
Txi_gene <- tximport(path, 
                     type = "kallisto", 
                     tx2gene = Tx.Ss, 
                     txOut = FALSE, #How does the result change if this =FALSE vs =TRUE?
                     countsFromAbundance = "lengthScaledTPM",
                     ignoreTxVersion = FALSE)
print("Data Import Complete")
